version: '2'

services:
  tyro-api:
    image: tyrocr.azurecr.io/tyro-api-niall:12
    ports:
      - 8082:8082
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker

  postgres:
    image: tyrocr.azurecr.io/tyro-testdb:05-08-2023--39
    container_name: local-test-api-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
