version: '2'

services:
  tyro-api:
    image: tyrocr.azurecr.io/test-api-niall:6-calendar
    ports:
      - 8082:8082
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker

  postgres:
    image: tyrocr.azurecr.io/tyro-testdb:03-08-2023--35
    container_name: local-test-api-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
