version: '3'

services:
  tyro-api:

    image: tyrocr.azurecr.io/tyro-api-niall:123dh7gw    # <--- api
    ports:
      - 8082:8082
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: docker

  postgres:
    image:  tyrocr.azurecr.io/tyro-testdb:05-25-2023--46 # <--- database
    container_name: local-test-api-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"