export enum PROFILE_TYPE_NAMES {
  TURO_ADMIN = 'Super Tyro',
  ADMIN = 'ADMIN',
  TEACHER = 'TEACHER',
  CONTACT = 'CONTACT',
  STUDENT =  'STUDENT',
}

export enum HEADERS {
  TENANT = 'X-TENANT-ID',
  PARTY_ID = 'X-PARTY-ID',
}
