name: Pull request build

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: c-hive/gha-yarn-cache@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: 'yarn build'
        run: |
          yarn install
          yarn build
